language: node_js
cache: yarn
node_js:
- node
script: yarn start & yarn test
deploy:
  provider: npm
  email: npm@netflix.com
  on:
    tags: true
  api_key:
    secure: QEXoDUYKGaMsT/ch92SorWYqOGaP3lgcrQvVlHA696MCshJdGQsCyzoA8D7PnnabrVy5m2vGexWktmGc36zuaWwhaRUBNTaReTd7RrzAkG078bl19ngsFmebmi3um1E0Ughca57XF1++Mf9k+NAaFLZ+xvz1h2vcuHGBC8yS4GiLseCMDhWggczKGdbPuUULGrNYwYMAYdIUqgHS8TUpT/oCY5lgNHZBVKDVkoyCYq2L4DJS+rjhbvBIj9rRrE7Qk+ds2yevYscb12VStnFYNuG1oBXHxYuNdh7mmVH8Z41j1wViXbWvlj6WDFLQzUNGGPxCkNMV6PN5DBU2AzJX4mrTZtObJgWq7Uw6uRG3DWCjbjgHPJLWnownWdK9QvbMDUtQwEvU7sozqJG0XPvT5Pp8BuhWs45VlS0ZQfx3PLZ48clqWddvZ6zKMoQy//H929zPTL7q80MKpAlUK5tTP+G5ySRHxyRKfXelMhWdpmq1HRV06sv1DuDFFsJyIBgfFZIOBdDH45opHIUid1Tp6VmbnH0JcC5WjeTvwQI/MqjWOlzkWGQFHpMK6KZsvFEWvhBnkhVB8CoF9sMNks4wSlj9lQYk3gBs2vX4zh8IYHOn4Kp8bO4n370ZontaXSN7inwTbyZacGQtEWMJeUCoQbU75dewhsLsvNvYp/AmH0Q=
